### ISSUE TITLE
Issue with using prefixes with spatial resolution URIs

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dark-data-rules-generation#2]
I should have noticed this earlier, but we cannot use a prefix for spatial resolution URIs.  The part after the prefix cannot start with a number, therefore `ddspatial:2+x+2.5+deg.` is not a legal URI.  For spatial URIs we will have to just use the full URI.
- illegal: `ddspatial:2+x+2.5+deg.`
- legal: `<http://darkdata.tw.rpi.edu/data/spatial-resolution/2+x+2.5+deg.>`

**Comment by anirudhprabhu** [comment]
Just fixed it.
