### ISSUE TITLE
Verify class names from ontology with class names in rules

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dark-data-rules-generation#4]
We should check to ensure the phenomena class name referenced in the rules match the class names from the ontology.

For example, "Fire" in the google doc should be `dd:Wildfire` in the rules.

See https://github.com/tetherless-world/darkdata-rule-service/blob/master/src/main/resources/rdf/darkdata.ttl for the most recent version of the ontology in use by the service.

**Comment by anirudhprabhu** [comment]
while checking the ontology, i found this labeling mistake
`###  http://www.purl.org/twc/ns/darkdata#DustAndHaze

dd:DustAndHaze rdf:type owl:Class ;

```
           rdfs:label "Wildfire"@en ;

           rdfs:subClassOf dd:Phenomena ;

           dd:topic "Dust and Haze" ;

           rdfs:seeAlso <http://eonet.sci.gsfc.nasa.gov/api/v1/topics/7> .`
```

The Label should be `rdfs:label "Dust and Haze"@en ;` right?

**Comment by zednis** [comment]
yep, I will update the label for `dd:DustAndHaze` in the ontology.

**Comment by anirudhprabhu** [comment]
Fixed this.
